name: .NET Framework Build

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'   # ex: v1.0.0 créera une release automatique
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]

    env:
      Solution_Name: RetroBat/RetroBat.sln   # solution principale

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    - name: Build solution
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU" /verbosity:minimal

    # Upload artifacts pour téléchargement manuel
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RetroBat-${{ matrix.configuration }}
        path: |
          RetroBat/**/bin/${{ matrix.configuration }}/

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/**/RetroBat.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
